//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encomienda
    {
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public string Destino { get; set; }
        public string PuntoSalida { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public System.DateTime FechaLlegada { get; set; }
        public string TipoProducto { get; set; }
        public float Peso { get; set; }
        public float Largo { get; set; }
        public float Alto { get; set; }
        public float Ancho { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public decimal Precio { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
